### ISSUE TITLE
error "pip: command not found"

### ISSUE THREAD

**Issue by Jmuccigr** [mromanello/CitationExtractor#17]
Running the installer on High Sierra and got this error from the macOS installer for the last three lines of the file. Should this now read `pip3`?

**Comment by mromanello** [comment]
Hi @Jmuccigr ! in fact, although py3 support is planned for the near future, for the time being the library supports py2 only (I know...). But as soon as there is a good test coverage I can start looking into the migration!

**Comment by Jmuccigr** [comment]
I've got python installed via homebrew and right now `pip` is `pip2`, so I tried that and it worked fine. You might throw in a check for the pip and pip2 commands.

Now, off to figure out how I run the darn thing...

**Comment by mromanello** [comment]
the lack of documentation is still a major limitation of this library... Do shoot me an email (name do lastname at epfl dot ch) and I'm happy to help you, also sharing notebooks that I have etc. One day (hopefully not too far away in time) it will all be online and nicely documented ;-)
